apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  selector:
    matchLabels:
      app: django
  replicas: 1
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: tonkiuter/tonkiuter-django:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
          - name: DJANGO_ALLOWED_HOSTS
            valueFrom: 
              secretKeyRef:
                name: django-config
                key: DJANGO_ALLOWED_HOSTS
              
---
apiVersion: v1
kind: Service
metadata: 
  name: django-service
spec:
  type: LoadBalancer
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000