# Generated by Django 3.2.4 on 2021-09-06 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='portfolio',
            managers=[
            ],
        ),
    ]
