# Generated by Django 3.2.4 on 2021-10-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_invest'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
