# Generated by Django 3.2.4 on 2021-10-27 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invest_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='dateInvest',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 17, 16, 13, 447897)),
        ),
    ]
