# Generated by Django 3.2.4 on 2021-10-28 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_invest_dateinvest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invest',
            name='dateInvest',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
