# Generated by Django 3.2.4 on 2021-07-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_id', models.CharField(max_length=20)),
                ('ticker_name', models.CharField(max_length=20)),
            ],
        ),
    ]
