# Generated by Django 3.2.4 on 2021-09-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_rename_tickets_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mex_stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=100)),
                ('stock_name', models.CharField(max_length=100)),
            ],
        ),
    ]
